apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: superior-duck-go 
  janus-idp.io/tekton: superior-duck-go
  backstage.io/kubernetes-id: superior-duck-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: superior-duck-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  